service: udemy-aws-lambda
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-api-gateway-throttling
  - serverless-iam-roles-per-function
  - serverless-s3-sync

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 10
    maxConcurrentRequests: 5
  bucketName: udemy-aws-lambda-418581597558
  s3Sync:
    buckets:
      - bucketName: ${self:custom.bucketName}
        localDir: static

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1
  httpApi:
    cors:
      allowedOrigins:
        - 'http://${self:custom.bucketName}.s3-website-ap-northeast-1.amazonaws.com'
        - 'http://localhost:3000'

functions:
  first:
    handler: first.hello
  second:
    handler: second.hello
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          method: get
          path: /hello
  getItems:
    handler: src/itemhandler.getItems
    events:
      - httpApi:
          method: get
          path: /getItems
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: 'arn:aws:dynamodb:*:*:table/items'
  getImage:
    handler: src/imagehandler.getImage
    events:
      - httpApi:
          method: get
          path: /getImage
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: 'arn:aws:s3:::aws-lambda-images-418581597558'
  updateTaskById:
    handler: src/taskhandler.updateTaskById
    events:
      - httpApi:
          method: patch
          path: /updateTaskById
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: 'arn:aws:dynamodb:*:*:table/tasks'
  deleteTaskById:
    handler: src/taskhandler.deleteTaskById
    events:
      - httpApi:
          method: delete
          path: /deleteTaskById
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: 'arn:aws:dynamodb:*:*:table/tasks'
  getTaskById:
    handler: src/taskhandler.getTaskById
    events:
      - httpApi:
          method: get
          path: /getTaskById
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: 'arn:aws:dynamodb:*:*:table/tasks'
  taskList:
    handler: src/taskhandler.list
    events:
      - httpApi:
          method: get
          path: /tasks
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: 'arn:aws:dynamodb:*:*:table/tasks'
          
  taskPost:
    handler: src/taskhandler.post
    events:
      - httpApi:
          method: post
          path: /tasks
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: 'arn:aws:dynamodb:*:*:table/tasks'

resources:
  Resources:
    UsersDynamoDBTable: 
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: users
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
    ItemsDynamoDBTable: 
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: items
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
    TasksDynamoDBTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tasks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    StaticSiteS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSiteS3Bucket
        PolicyDocument: 
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource:
                'arn:aws:s3:::${self:custom.bucketName}/*'
